apiVersion: v1
kind: Secret
metadata:
  name: puzzlezen-secrets
  namespace: puzzlezen
type: Opaque
stringData:
  postgres-password: "puzzlezen_secret"
  redis-password: "puzzlezen_secret"
  jwt-secret: "CHANGE_ME_IN_PROD_USE_A_REAL_256_BIT_KEY"
  mongo-password: "puzzlezen_secret"
